README.md
button-card.js

I wanted to have an option to defined different icons based on state but then I realized that sometimes the entity already contains the icon information as an attribute. 
If you already customized the entity with your own icon it can fetch that attribute directly from the entity instead of defining it again.
In my scenario I wanted to show different icons based on my template cover state. The template cover already have a state_open and state_close icon.
So if you add `icon: attribute` it will look for the "icon" attribute in the entity.
I´m not familiar with javascript so the code might not be optimal but it´s working. Feel free to adjust if there is a better way.

Added option to use entity icon

---

button-card.js

So this is more of a feature request, my coding is quite limited and this is my first ever PR so sorry if its not correct.
basicly this fuctionality adds the ability to set hex color option in ui-lovelace like this : 
`color: "#1affa3"`
I assumed this would also work for setting "var(--primary-color)" but it does not (only works for direct hex value) and that is the limit of my ability.
the reason for this request is so that button colors can bet set to theme variables and thus become dynamic with theme change.
Thanks.

dynamic color options

---

README.md
button-card.js

Will use the icon of the current state if set, use main icon otherwise.
It brings back the functionality of the icon defined in a state, broken in current release.

Fix issue #38 - use state icon if provided

---

button-card.js

Went through a few iterations discussed in #57 and #60. The gist of the changes are...
1) get LitElement from `home-assistant-main` instead of `hui-error-entity-row`
2) create an additional custom element named `button-card-button` which will be based on `mwc-button` if available, otherwise fallback to `paper-button`
3) override a couple of the `mwc-button`'s styles to allow for variable height and font color inheriting
4) moved the styles to come from a static method, so they are no longer duplicated
5) wrap everything in a closure to prevent polluting the `window` and avoid conflicts with `window`
The result looks like this...

updating to support HA 0.88

---

README.md
button-card.js

Hi,
This PR, adds operator configuration to state.
Extract from documentation:
The definition order matters, the first item to match will be the one selected.
```yaml
- type: "custom:button-card"
entity: sensor.temperature
show_state: true
state:
- value: 15
operator: '<='
color: blue
- value: 25
operator: '>='
color: red
- operator: 'default' # used if nothing matches
color: yellow
```
Available operators (See updated documentation for details):
* `<`
* `<=`
* `==`
* `>=`
* `>`
* `!=`
* `regex`
* `default`

Add operators to state

---

README.md

input_selects do not support toggle, updated the example code to a confirmed working one using `input_select.select_next` service. 
Also fixed minor typo in tap_action section (swith = switch)

Fixed input_select code example, fixed minor typo

---

README.md

This adds `show_icon: false` to the "no icon" text only configuration example. 
This line is necessary now because after recent changes the card automatically uses the default icon for that entity_id as a fallback if there's no mdi: icon specified. 
Issue was pointed out by arsaboo in [this forum post](https://community.home-assistant.io/t/lovelace-button-card/65981/595) and has a screenshot of how it looks without this line.

adds show_icon: false to the text-only config example

---

README.md

Original commit used `location` but it was later changed to `navigate` to be more consistent with HA core. This just fixes docs to match the finalized naming scheme. 
Also added a note that navigation_path can link to internal HA URL's.

tap_action location was changed to navigate

---

README.md
button-card.js

Support for `url` as an action. Fix #87 
```yaml
- type: "custom:button-card"
icon: mdi:link
name: url
tap_action:
action: url
url: https://www.google.com
```

Support for URL in tap_action

---

button-card.js

Cleanup the code to delete the unneeded custom element. Replaced by a bunch of div. This fixes most if not all the issues introduced by the `mwc-button`.
* It fixes the button staying selected after a click (Fix #93)
* It fixes misalignment issues (Fix #89)
* Introduce the same ripple effect as the default button
Everything else stays exactly the same! :)

Get rid of the custom element

---

README.md
button-card.js

Fallback to simple click support when longpress is not found.
Warning in the documentation.

Fallback to simple click if longpress is not found

---

README.md
dist/button-card.js
src/button-card.ts
src/types.ts

* New option: `unlock_users`: A list of usernames allowed to unlock the button when `lock: true`. If undefined, everyone is allowed. (Fixed #167)
```yaml
- type: custom:button-card
entity: switch.super_secure_switch
lock: true
unlock_users:
- user1
- user2
```

Only specific users can disable the lock

---

README.md
src/button-card.ts

Fixes #618, Fixes #558, Fixes #368

feat(templates): Support for one time evaluation of js templates in `triggers_update` and `entity`

---

src/action-handler.ts

Found this while working though touch events. A straighforward non-breaking change that fixes an issue. Can be tested by putting Chrome in touch device mode in developer console.
Video with PR:
https://github.com/user-attachments/assets/a5dc5b46-d60a-4180-9443-3aebc8a95f46

fix: Move while hold on touch devices

---

README.md
package.json
src/action-handler.ts
src/button-card.ts
src/styles.ts
src/types/homeassistant.ts
test/ui-lovelace.yaml
yarn.lock

BREAKING CHANGE: CSS variables `--mdc-ripple-*` are no longer supported. These have been replaced with `--button-card-ripple-*` variables. You will need to update your configuration.
Closes #887

feature(actions): migrate to ha-ripple

---

README.md
src/button-card.ts
src/types/types.ts
test/ui-lovelace.yaml

BREAKING CHANGE: Some of you were using hacks to execute javascript actions. This release officially implements `action: javascript` and this is the **only supported** way to execute javascript actions going forward. Any other configuration might execute the javascript action while the card is first displayed. Please update your config accordingly and read the updated documentation.
Closes #1021

feat(actions): Official support for native javascript actions

---

src/styles.ts

fix(tooltip): Set default z-index so long/wide tooltips are always visible.

---

README.md
src/button-card.ts
src/styles.ts
src/types/types.ts
test/ui-lovelace.yaml

```yaml
- type: 'custom:button-card'
entity: script.delay_script
name: Spinner script main
tap_action:
action: perform-action
perform_action: script.delay_script
show_label: state
spinner: '[[[ return entity.state === "on" ]]]'
- type: 'custom:button-card'
entity: script.delay_script
name: Spinner script state
tap_action:
action: perform-action
perform_action: script.delay_script
show_label: state
styles:
spinner:
- pointer-events: none !important # unlocks the interaction with the card
- --button-card-spinner-background-color: none # removes the partially opaque overlay
state:
- value: 'on'
spinner: true
styles:
spinner:
- --button-card-spinner-color: red # make the spinner red
```

feat(spinner): Display a configurable spinning wheel (eg. while a script is running)

---

README.md
src/button-card.ts
src/types/types.ts
test/ui-lovelace.yaml

feat(protect): Support for `success_message`

---

README.md
src/button-card.ts
src/types/types.ts
test/ui-lovelace.yaml

```yaml
type: custom:button-card
entity: light.aquarium
protect: # globally enables the PIN for all actions
pin: '1234'
success_message: 'PIN is correct!'
failure_message: 'PIN is wrong!'
tap_action:
action: toggle
hold_action:
action: perform-action
perform_action: switch.toggle
target:
entity_id: switch.aquarium_pump
icon_tap_action:
action: more-info
entity: sensor.aquarium_temperature
protect:
pin: '' # Setting this to an empty string disables the pin for this action only.
```
Closes #1044

feat(protect): allow configuring `protect` at the card level
