- button-card.js
You should never change the Lovelace config.
This PR makes a copy of the config before changing it and adding things.
You where adding an optional parameter `state` to the config, since this is optional it could be undefined. Undefined cannot be mapped to YAML, thus breaking the YAML editors of Lovelace.
> Don't edit Lovelace config

- README.md
New instructions for `custom_updater` to take advantage of ["super_custom_cards"](https://github.com/custom-components/custom_updater/wiki/super_custom-cards)
> Update instructions for custom_updater

- README.md
- button-card.js
New option `confirmation` that produces a popup confirmation dialog
> Add confirmations

- README.md
- button-card.js
Fixes https://github.com/custom-cards/button-card/issues/90
> Add spin option to state object

- button-card.js
> Match HA rounded corner default style

- button-card.js
Fixes #114 and supports `card-modder` now
> card-modder-support

- README.md
changed "service" to "call-service", realizing this error took longer than it should have :)
> Correct mistake in examples

- README.md
Updating readme to include documentation for repeating `hold_action`.
> Update with repeat documentation

- README.md
- dist/button-card.js
- package-lock.json
- package.json
- rollup.debug.config.js
- src/button-card.ts
- src/handle-click.ts
- src/helpers.ts
- src/types.ts
* Configuration templating support:
* Define your config template in the main lovelace configuration and then use it in your button-card. This will avoid a lot of repetitions! It's basically YAML anchors, but without using YAML anchors and is very useful if you split your config in multiple files 😄 
* You can overload any parameter with a new one, **appart from the states**. The state arrays in templates will be concatenated together with your config, meaning you can **add** new states but not change/delete states. Your main config states will be appended to the ones in the template.
* You can also inherit another template from within a template.
In `ui-lovelace.yaml` (or in another file using `!import`)
```yaml
button_card_templates:
header:
styles:
card:
- padding: 5px …
```
> Config template support

- .circleci/config.yml
- dist/button-card.js
- src/button-card.ts
**FIXES**
* Fix ripple effect when lock is true
> Fix ripple when lock is true

- README.md
- dist/button-card.js
- src/button-card.ts
* Adds the CSS variable `--button-card-light-color-no-temperature` equivalent to `--button-card-light-color` but without the color temperature applied.
> New css variable for light color without temperature

- dist/button-card.js
- src/button-card.ts
**FIXES**
* Fixes #177: `name_template` and `entity_picture_template` where not updating on state change
> Fix some templates not updating on changes

- dist/button-card.js
- src/button-card.ts
* Support for `timer` entities. It will now display the time remaining while running or paused and idle while being idle. Fixes #156
> Support for timer entities

- dist/button-card.js
- src/button-card.ts
* Support for HTML in `name` or `name_template`
> Support for HTML in name

- dist/button-card.js
- src/button-card.ts
**BUGFIXES**
* If a field with template support had the number `0` as a value, the field's value would be transformed into `undefined`
* When in an `*_action` the `service_data` field contained parameters which where objects, an error was thrown and the action wouldn't execute.
> Fix for 2.0.0

- dist/button-card.js
- package-lock.json
- package.json
- rollup.config.js
- rollup.debug.config.js
- src/button-card.ts
- src/long-press.ts
**BUGFIXES**
* Fix when a "templatable" field had the `null` value
* IOS 13 strange tap behaviour should be fixed now!
> Fixes #206, Fixes #195

- README.md
Links to awesome tutorials using this card. :)
> Community-links

- README.md
Hello All,
Would like to submit a pull for a spelling update in the readme
Update livimg_room_speaker to living_room_speaker on lines 1011 ad 1020
> Fix spelling in code example

- README.md
Look at the changes in the diff view.
> Note HACS is supported and fix typo

- README.md
> Various typos and fixes

- README.md
This PR being merged means the project is still maintained.
> Update maintainence badge

- README.md
and explicitly link to the haptic feedback section
> link to 'official' iOS companion app

- README.md
Edit enclose quote in lock example otherwise return an error
> minor quotes correction

- README.md
> Readme update - manual installation note for javascript file being blocked.

- README.md
- src/button-card.ts
- test/ui-lovelace.yaml
Closes #850 
Closes #611 
Closes #543 
Provides another solution for #616 
... and maybe some more.
Readme changes describes what is possible with examples.
> Allow action to be a template string

- README.md
> Update card_mod example configuration in README.md

- src/button-card.ts
- src/helpers.ts
- src/types/homeassistant.ts
- src/types/types.ts
> Support media-source:// for picture_entity

- src/button-card.ts
> fix: Hold action on picture entity

- src/button-card.ts
> fix: Event propagation to parent would not propagate the event properties

- src/button-card.ts
> fix: Type error when using actions in templates

- src/button-card.ts
> fix(actions): complex templates would break in specific cases
